"""5 migration

Revision ID: 8c2ba7dfc962
Revises: 92d8e5704cff
Create Date: 2022-03-05 21:10:23.581346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2ba7dfc962'
down_revision = '92d8e5704cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('started_at', sa.DateTime(), server_default='now()', nullable=True))
    op.add_column('game', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.drop_column('game', 'chat_id')
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=True))
    op.drop_constraint('user_vk_id_key', 'user', type_='unique')
    op.drop_column('user', 'vk_id')
    op.drop_column('user', 'name')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('vk_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_vk_id_key', 'user', ['vk_id'])
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.add_column('game', sa.Column('chat_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('game', 'finished_at')
    op.drop_column('game', 'started_at')
    # ### end Alembic commands ###
