"""6 migration

Revision ID: a5523465b26d
Revises: 8c2ba7dfc962
Create Date: 2022-03-05 21:11:17.151415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5523465b26d'
down_revision = '8c2ba7dfc962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('vk_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['vk_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'vk_id')
    op.drop_column('game', 'chat_id')
    # ### end Alembic commands ###
