"""3rd migration

Revision ID: d20316007ea4
Revises: 52a7aecd7df1
Create Date: 2022-02-25 23:07:04.501440

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from app.quiz.models import StatusGame

revision = 'd20316007ea4'
down_revision = '52a7aecd7df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(StatusGame, impl=sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'status')
    # ### end Alembic commands ###
